# render.yaml – Full blueprint for frontend and backend

staticSites:
  - name: scoregenius-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://score-genius-backend.onrender.com
    routes:
      - type: rewrite
        source: /app
        destination: /app.html
      - type: rewrite
        source: /app/*
        destination: /app.html
      - type: rewrite
        source: /*
        destination: /index.html

services:
  - type: web
    name: scoregenius-backend
    rootDir: backend/server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SUPABASE_URL
        from: env
      - key: SUPABASE_SERVICE_KEY
        from: env
