services:
  - type: web
    name: score-genius-backend
    rootDir: .                      # repo root
    buildCommand: |
      cd frontend
      npm ci && npm run build       # ↩️ produces frontend/dist
      cd ..                         # ← return to repo root
      cd backend/server
      npm install
      cd ../..                      # ← return again so slug = entire repo
    startCommand: node backend/server/server.js
    envVars:
      - key: VITE_API_BASE_URL
        value: http://localhost:3001 # during runtime, Express will proxy API requests
      - key: SUPABASE_URL
        from: env
      - key: SUPABASE_SERVICE_KEY
        from: env
