services:
  - type: web
    name: score-genius-backend
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: VITE_API_BASE_URL
        value: http://localhost:3001
      - key: SUPABASE_URL
        from: env
      - key: SUPABASE_SERVICE_KEY
        from: env
    ports:
      - 10000
