# render.yaml – Static Site + SPA rewrites
staticSites:
  - name: scoregenius-frontend
    rootDir: frontend # where package.json and vite.config.ts live
    buildCommand: npm ci && npm run build
    staticPublishPath: dist # where Vite writes its build
    envVars:
      - key: VITE_API_BASE_URL
        value: https://score-genius-backend.onrender.com

    # SPA rewrites
    routes:
      - type: rewrite # /app (no slash) → app.html
        source: /app
        destination: /app.html
      - type: rewrite # /app/* → app.html (client-side router)
        source: /app/*
        destination: /app.html
      - type: rewrite # everything else → index.html (marketing site)
        source: /*
        destination: /index.html
