services:
  - type: web
    name: score-genius-backend
    rootDir: .
    buildCommand: |
      # ── front-end build ──────────────────────────────
      cd frontend
      npm ci && npm run build          # → creates frontend/dist
      cd ..                            # back to repo root

      # move (not copy) the entire dist folder into backend/server
      rm -rf backend/server/static     # clean old build if it exists
      mv frontend/dist backend/server/static

      # ── back-end deps ───────────────────────────────
      cd backend/server
      npm install
    startCommand: node backend/server/server.js
    envVars:
      - key: VITE_API_BASE_URL
        value: http://localhost:3001
      - key: SUPABASE_URL
        from: env
      - key: SUPABASE_SERVICE_KEY
        from: env
