# render.yaml (at repo root)
staticSites:
  - rootDir: frontend
    buildCommand: npm ci && npm run build
    publishDir: dist
    redirects:
      - source: "/app"
        destination: "/app.html"
        status: 200
      - source: "/app/*"
        destination: "/app.html"
        status: 200
      - source: "/*"
        destination: "/index.html"
        status: 200
