openapi: 3.0.3
info:
  title: ScoreGenius NFL API
  version: 1.0.0
  description: REST API for NFL analytics endpoints used by ScoreGenius PWA
servers:
  - url: /api/v1
paths:
  /schedule:
    get:
      summary: Fetch NFL schedule or historical results for a given date
      parameters:
        - in: query
          name: date
          schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2}$'
          required: true
          description: Date in YYYY-MM-DD format
      responses:
        "200":
          description: Array of schedule or historical games
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  retrieved:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/ScheduleEntry"
        "400":
          $ref: "#/components/responses/BadRequest"
  /snapshots:
    get:
      summary: Fetch multiple game snapshots by comma-separated IDs
      parameters:
        - in: query
          name: gameIds
          schema:
            type: string
          required: true
          description: Comma-separated list of game_id strings
      responses:
        "200":
          description: Array of snapshot objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Snapshot"
        "400":
          $ref: "#/components/responses/BadRequest"
  /snapshots/{gameId}:
    get:
      summary: Fetch single game snapshot by ID
      parameters:
        - in: path
          name: gameId
          schema:
            type: string
          required: true
          description: game_id to retrieve snapshot
      responses:
        "200":
          description: Snapshot object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Snapshot"
        "404":
          $ref: "#/components/responses/NotFound"
  /teams/{season}/full:
    get:
      summary: Fetch full season stats (including playoffs) for teams
      parameters:
        - in: path
          name: season
          schema:
            type: integer
          required: true
        - in: query
          name: teamId
          schema:
            type: string
          description: Comma-separated list of team IDs
        - in: query
          name: conference
          schema:
            type: string
          description: AFC or NFC
        - in: query
          name: division
          schema:
            type: string
          description: East, West, North, South
      responses:
        "200":
          description: Array of team season stats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TeamSeasonStats"
        "400":
          $ref: "#/components/responses/BadRequest"
  /teams/{season}/regonly:
    get:
      summary: Fetch regular-season stats for teams
      parameters:
        - $ref: "#/components/parameters/season"
        - $ref: "#/components/parameters/teamId"
        - $ref: "#/components/parameters/conference"
        - $ref: "#/components/parameters/division"
      responses:
        "200":
          description: Array of team season stats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TeamSeasonStats"
        "400":
          $ref: "#/components/responses/BadRequest"
  /teams/{season}/dashboard:
    get:
      summary: Fetch dashboard card metrics for teams
      parameters:
        - $ref: "#/components/parameters/season"
        - $ref: "#/components/parameters/teamId"
        - $ref: "#/components/parameters/conference"
        - $ref: "#/components/parameters/division"
      responses:
        "200":
          description: Dashboard card data
          content:
            application/json:
              schema:
                type: object
                properties:
                  season:
                    type: integer
                  retrieved:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/DashboardCard"
  /teams/{season}/sos:
    get:
      summary: Fetch Strength-of-Schedule for teams
      parameters:
        - $ref: "#/components/parameters/season"
        - $ref: "#/components/parameters/teamId"
        - $ref: "#/components/parameters/conference"
        - $ref: "#/components/parameters/division"
      responses:
        "200":
          description: Array of SOS metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  season:
                    type: integer
                  retrieved:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SosEntry"
  /teams/{season}/srs:
    get:
      summary: Fetch Simple Rating System for teams
      parameters:
        - $ref: "#/components/parameters/season"
        - $ref: "#/components/parameters/teamId"
        - $ref: "#/components/parameters/conference"
        - $ref: "#/components/parameters/division"
      responses:
        "200":
          description: Array of SRS metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  season:
                    type: integer
                  retrieved:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SrsEntry"
  /health/cron:
    get:
      summary: Check cron job health
      responses:
        "200":
          description: Cron health payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  lastRun:
                    type: string
                    format: date-time
                  status:
                    type: string
  /health/validate:
    get:
      summary: Validate team aggregation via RPC
      responses:
        "200":
          description: Validation payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  checks:
                    type: array
                    items:
                      type: string
                  errors:
                    type: array
                    items:
                      type: string
  /nfl/team-stats/summary:
    get:
      summary: Fetch consolidated NFL team summary (advanced + SRS + SoS) for a season
      parameters:
        - in: query
          name: season
          schema:
            type: integer
          required: true
          description: Season year (e.g., 2024)
      responses:
        "200":
          description: Team summary array
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NflTeamSummaryResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
  /nfl/team-stats/advanced:
    get:
      summary: Fetch NFL advanced team statistics for a season
      parameters:
        - in: query
          name: season
          schema:
            type: integer
          required: true
          description: Season year (e.g., 2024)
      responses:
        "200":
          description: Advanced stats array
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NflAdvancedStatsResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
components:
  parameters:
    season:
      in: path
      name: season
      schema:
        type: integer
      required: true
    teamId:
      in: query
      name: teamId
      schema:
        type: string
      description: Comma-separated team IDs
    conference:
      in: query
      name: conference
      schema:
        type: string
      description: AFC or NFC
    division:
      in: query
      name: division
      schema:
        type: string
      description: East, West, North, South
  schemas:
    ScheduleEntry:
      type: object
      properties:
        id:
          type: string
        gameDate:
          type: string
          format: date
        dataType:
          type: string
          enum:
            - schedule
            - historical
        status:
          type: string
        homeTeamId:
          type: integer
        awayTeamId:
          type: integer
        # ── fields present for upcoming games ──
        scheduledTimeUTC:
          type: string
          format: date-time
        spreadLine:
          type: number
          nullable: true
        totalLine:
          type: number
          nullable: true
        predictedHomeScore:
          type: number
        predictedAwayScore:
          type: number
        # ── fields present for completed games ──
        finalHomeScore:
          type: integer
        finalAwayScore:
          type: integer
        homeQ:
          type: array
          items:
            type: integer
        awayQ:
          type: array
          items:
            type: integer
    Snapshot:
      type: object
      properties:
        game_id:
          type: string
        game_date:
          type: string
          format: date
        season:
          type: integer
        headline_stats:
          type: array
        bar_chart_data:
          type: array
        radar_chart_data:
          type: array
        pie_chart_data:
          type: array
        last_updated:
          type: string
          format: date-time
    TeamSeasonStats:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        wins:
          type: integer
        losses:
          type: integer
    DashboardCard:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        PF:
          type: integer
        PA:
          type: integer
        YdsPerPlay:
          type: number
        TOsPerGame:
          type: number
        WinPctHome:
          type: number
        WinPctAway:
          type: number
        SOSRank:
          type: integer
    SosEntry:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        sosPct:
          type: number
        sosRank:
          type: integer
    SrsEntry:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        netRating:
          type: number
    NflTeamSummaryEntry:
      type: object
      properties:
        team_id:
          type: integer
        team_name:
          type: string
        season:
          type: integer
        srs:
          type: number
        sos:
          type: number
        sos_rank:
          type: integer
        win_pct:
          type: number
        pythagorean_win_pct:
          type: number
        avg_third_down_pct:
          type: number
        avg_red_zone_pct:
          type: number
        avg_yards_per_drive:
          type: number
        avg_turnovers_per_game:
          type: number
        avg_time_of_possession:
          type: string
    NflAdvancedStatsEntry:
      type: object
      properties:
        team_id:
          type: integer
        team_name:
          type: string
        season:
          type: integer
        avg_third_down_pct:
          type: number
        avg_red_zone_pct:
          type: number
        avg_yards_per_drive:
          type: number
        avg_turnovers_per_game:
          type: number
        pythagorean_win_pct:
          type: number
        avg_time_of_possession:
          type: string
    NflTeamSummaryResponse:
      type: object
      properties:
        season:
          type: integer
        retrieved:
          type: integer
        data:
          type: array
          items:
            $ref: "#/components/schemas/NflTeamSummaryEntry"
    NflAdvancedStatsResponse:
      type: object
      properties:
        season:
          type: integer
        retrieved:
          type: integer
        data:
          type: array
          items:
            $ref: "#/components/schemas/NflAdvancedStatsEntry"
  responses:
    BadRequest:
      description: Invalid parameter
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
