-- supabase/migrations/000_create_nba_historical_game_stats.sql
-- Base table for NBA historical game stats used by rolling views

CREATE TABLE IF NOT EXISTS nba_historical_game_stats (
  id                 SERIAL PRIMARY KEY,
  game_id            INTEGER    NOT NULL,
  home_team          TEXT       NOT NULL,
  away_team          TEXT       NOT NULL,
  home_score         INTEGER,
  away_score         INTEGER,
  home_q1            INTEGER,
  home_q2            INTEGER,
  home_q3            INTEGER,
  home_q4            INTEGER,
  home_ot            INTEGER,
  away_q1            INTEGER,
  away_q2            INTEGER,
  away_q3            INTEGER,
  away_q4            INTEGER,
  away_ot            INTEGER,
  game_date          DATE,
  updated_at         TIMESTAMPTZ DEFAULT NOW(),
  home_assists       INTEGER,
  home_steals        INTEGER,
  home_blocks        INTEGER,
  home_turnovers     INTEGER,
  home_fouls         INTEGER,
  away_assists       INTEGER,
  away_steals        INTEGER,
  away_blocks        INTEGER,
  away_turnovers     INTEGER,
  away_fouls         INTEGER,
  home_off_reb       INTEGER,
  home_def_reb       INTEGER,
  home_total_reb     INTEGER,
  away_off_reb       INTEGER,
  away_def_reb       INTEGER,
  away_total_reb     INTEGER,
  home_3pm           INTEGER,
  home_3pa           INTEGER,
  away_3pm           INTEGER,
  away_3pa           INTEGER,
  home_fg_made       INTEGER,
  home_fg_attempted  INTEGER,
  away_fg_made       INTEGER,
  away_fg_attempted  INTEGER,
  home_ft_made       INTEGER,
  home_ft_attempted  INTEGER,
  away_ft_made       INTEGER,
  away_ft_attempted  INTEGER
);
