# .github/workflows/ablation.yml
name: Ablation

on:
  workflow_dispatch: {}
  #schedule:
  #- cron: "0 5 * * 1" # every Monday 05:00 UTC

concurrency:
  group: ablation-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ablate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

      - name: Install deps
        run: pip install -r backend/requirements.txt

      - name: Run ablation
        run: make ablate

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ablation_results
          path: reports/ablation_results.json
