# .github/workflows/backend_ci.yml
name: Backend CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # Daily at 04:00 UTC
  pull_request:
    branches: [master]
    paths:
      - "backend/**"
      - "supabase/**"
      - ".github/workflows/backend_ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  # 1) SQL-only linting (SQLFluff)
  lint-sql:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Exclude Supabase remote_schema migration
        run: rm -f supabase/migrations/*remote_schema*.sql
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-sqlfluff-${{ hashFiles('backend/requirements.txt') }}
      - name: Install SQLFluff
        run: |
          python -m pip install --upgrade pip
          pip install "sqlfluff[jinja]"
      - name: Lint migrations
        run: |
          files=$(find supabase/migrations -maxdepth 1 -type f \
            -regextype posix-extended \
            -regex '.*/[0-9]{3}_.*\.sql' \
            | sort)
          [[ -z "$files" ]] && echo "No migrations to lint – exiting." && exit 0
          echo "$files" | sed 's/^/  • /'
          sqlfluff lint $files

  # 2) Smoke-test migrations & materialized view
  test-migrations:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    needs: lint-sql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Exclude Supabase remote_schema migration
        run: rm -f supabase/migrations/*remote_schema*.sql

      - name: Install Postgres client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - uses: supabase/setup-cli@v1
        with:
          version: "1.60.0"

      - name: Start Supabase (DB only)
        run: supabase start --db-only

      - name: Wait for Postgres
        run: |
          for i in {1..15}; do
            pg_isready -h 127.0.0.1 -p 54322 -U postgres && break
            sleep 2
          done

      - name: Reset & apply migrations
        run: PGSSLMODE=disable supabase db reset

      - name: Stop Supabase
        if: always()
        run: supabase stop

  # 3) Python lint – diff-only
  python-lint-diff:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    needs: test-migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Determine changed Python files
        id: diff
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "files=" >> $GITHUB_OUTPUT
            exit 0
          fi
          base_ref="${{ github.event.pull_request.base.sha || github.event.before }}"
          if [[ -z "$base_ref" ]]; then
            echo "files=" >> $GITHUB_OUTPUT
            exit 0
          fi
          changed=$(git diff --name-only --diff-filter=ACMRT "$base_ref" HEAD -- 'backend/**/*.py' | tr '\n' ' ')
          echo "files=$changed" >> $GITHUB_OUTPUT
      - name: Run Ruff on changed files
        if: steps.diff.outputs.files != ''
        run: |
          echo "${{ steps.diff.outputs.files }}" | sed 's/^/  • /'
          ruff check ${{ steps.diff.outputs.files }}
      - name: Skip (no Python changes)
        if: steps.diff.outputs.files == ''
        run: echo "No Python files changed – skipping Ruff."

  # 4) Backend deps install (+ optional pytest)
  test-python-backend:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    needs: python-lint-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-python-${{ hashFiles('backend/requirements.txt') }}
      - name: Install dependencies
        run: pip install -r backend/requirements.txt
      #- name: Run FeatureEngine smoke tests
      #run: |
      #cd backend
      #pytest -q tests_smoke
