name: Ingest Historical Data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "10 4 * * *" # 04:10 UTC daily

jobs:
  ingest-historical:
    name: Run Historical‐only Pipelines
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r backend/requirements.txt

      - name: Run NBA game-stats historical ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python backend/data_pipeline/nba_game_stats_historical.py

      - name: Run NBA player-stats historical ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python backend/data_pipeline/nba_player_stats_historical.py

      - name: Run MLB game-stats historical ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python backend/data_pipeline/mlb_game_stats_historical.py

      - name: Run NBA team-stats historical ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python backend/data_pipeline/nba_team_stats_historical.py

      - name: Run MLB team-stats historical ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python backend/data_pipeline/mlb_team_stats_historical.py

      - name: Run NBA injuries ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
        run: python backend/data_pipeline/nba_injuries.py

      - name: Run Advanced Splits Population
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python backend/nba_features/populate_advanced_splits.py
