# .github/workflows/ingest_weather.yml
name: Ingest NFL Weather Snapshots

on:
  schedule:
    - cron: "30 11 * * *" # daily 11:30 UTC
  workflow_dispatch:
    inputs:
      lookahead_days:
        description: "WX_LOOKAHEAD_DAYS"
        default: "14"
        required: false
      lookback_days:
        description: "WX_LOOKBACK_DAYS"
        default: "0"
        required: false
      start_iso:
        description: "WX_START_ISO (optional fixed start)"
        default: ""
        required: false
      end_iso:
        description: "WX_END_ISO (optional fixed end)"
        default: ""
        required: false

concurrency:
  group: ingest-weather
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      WX_LOOKAHEAD_DAYS: ${{ github.event.inputs.lookahead_days || '14' }}
      WX_LOOKBACK_DAYS: ${{ github.event.inputs.lookback_days  || '0' }}
      WX_START_ISO: ${{ github.event.inputs.start_iso      || '' }}
      WX_END_ISO: ${{ github.event.inputs.end_iso        || '' }}
      TZ: UTC
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run weather ingest
        run: |
          set -euo pipefail
          WX_LOOKAHEAD_DAYS="${WX_LOOKAHEAD_DAYS}" \
          WX_LOOKBACK_DAYS="${WX_LOOKBACK_DAYS}" \
          WX_START_ISO="${WX_START_ISO}" \
          WX_END_ISO="${WX_END_ISO}" \
          npx ts-node --compiler-options '{"module":"commonjs","moduleResolution":"node","esModuleInterop":true,"skipLibCheck":true}' backend/data_pipeline/ingest_upcoming_weather.ts | tee ingest.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ingest-weather-${{ github.run_id }}
          path: ingest.log
