name: Ingest Preview Data

on:
  workflow_dispatch:
  schedule:
    - cron: "40 4 * * *" # 04:40 UTC daily

concurrency:
  group: ingest-previews-${{ github.run_id }} # 👈 unique per run
  cancel-in-progress: false

jobs:
  ingest-previews:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # whole job

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
      PYTHONUNBUFFERED: 1 # same as python -u

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: pip install -r backend/requirements.txt

      - name: Run MLB preview ingest
        run: |
          python -u -m backend.data_pipeline.mlb_games_preview \
            --days 1 --lookback 90

      - name: Run NBA preview ingest
        run: |
          python -u -m backend.data_pipeline.nba_games_preview \
            --days 1 --lookback 90 --no_calibrate --debug
