name: Ingest Preview Data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "50 4 * * *" # 04:50 UTC daily

jobs:
  ingest-previews:
    name: Run Preview‐only Pipelines
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r backend/requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run MLB preview ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python backend/data_pipeline/mlb_games_preview.py

      - name: Run NBA preview ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
        run: python backend/data_pipeline/nba_games_preview.py
