name: Ingest Preview Data

on:
  workflow_dispatch:
  schedule:
    - cron: "20 4 * * *" # 04:20 UTC daily
    - cron: "0 15 * * *" # 15:00 UTC daily

concurrency:
  group: ingest-previews-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ingest-previews:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
      PYTHONUNBUFFERED: 1
      LOG_LEVEL_OVERRIDE: ERROR
      CI: true
      PIP_DISABLE_PIP_VERSION_CHECK: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache undetected_chromedriver
        uses: actions/cache@v4
        with:
          path: ~/.local/share/undetected_chromedriver
          key: ${{ runner.os }}-uc-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uc-

      - name: Install deps
        run: pip install -r backend/requirements.txt

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Chrome version
        run: |
          echo "CHROME_PATH=$CHROME_PATH"
          "$CHROME_PATH" --version || google-chrome --version || true

      - name: Import smoke test
        run: |
          python - <<'PY'
          import httpx, dateutil.parser, undetected_chromedriver, selenium, bs4, requests
          print("import smoke ok")
          PY

      - name: Run MLB preview ingest (best-effort)
        run: |
          python -u -m backend.data_pipeline.mlb_games_preview || \
          echo "[WARN] MLB preview ingest failed but continuing"
        env:
          MLB_PITCHERS_REQUIRED: "false"

      - name: Run NBA preview ingest
        run: |
          python -u -m backend.data_pipeline.nba_games_preview \
            --days 1 --lookback 30 --no_calibrate

      - name: Run NFL Preseason preview ingest
        run: |
          python -u -m backend.data_pipeline.nfl_preseason_games_preview
