name: Refresh Remote Materialized Views

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 4 * * *"

jobs:
  refresh-remote-matviews:
    runs-on: ubuntu-latest
    env:
      # Use a single DATABASE_URL secret (your full Postgres URI)
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PGSSLMODE: require

    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Refresh NBA MV
        run: |
          psql "$DATABASE_URL" \
            --no-password \
            --set ON_ERROR_STOP=on \
            -c "REFRESH MATERIALIZED VIEW CONCURRENTLY public.nba_team_rolling_20_features;"

      - name: Smoke-test NBA
        run: |
          psql "$DATABASE_URL" \
            --no-password \
            --set ON_ERROR_STOP=on \
            -c "SELECT COUNT(*) FROM public.nba_team_rolling_20_features;"

      - name: Refresh MLB MV
        run: |
          psql "$DATABASE_URL" \
            --no-password \
            --set ON_ERROR_STOP=on \
            -c "REFRESH MATERIALIZED VIEW CONCURRENTLY public.mlb_team_rolling_10_features;"

      - name: Smoke-test MLB
        run: |
          psql "$DATABASE_URL" \
            --no-password \
            --set ON_ERROR_STOP=on \
            -c "SELECT COUNT(*) FROM public.mlb_team_rolling_10_features;"
