name: Refresh Remote Materialized Views

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *" # daily 04:30 UTC

jobs:
  refresh-matviews:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PGSSLMODE: require

    steps:
      - uses: actions/checkout@v4

      - name: Install psql + dig
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y postgresql-client dnsutils

      - name: Build IPv4-only connection URI
        id: ipv4
        run: |
          # pull hostname from DATABASE_URL
          HOST=$(echo "$DATABASE_URL" | sed -E 's#postgresql://[^@]+@([^:/]+).*#\1#')
          IPV4=$(dig +short A "$HOST" | head -1)

          echo "Using $HOST → $IPV4"
          DB_URL_V4=${DATABASE_URL//$HOST/$IPV4}

          # make it available to later steps
          echo "DB_URL_V4=$DB_URL_V4" >> "$GITHUB_ENV"

      - name: Refresh NBA & MLB materialized views
        run: |
          psql "$DB_URL_V4" --set ON_ERROR_STOP=on <<'SQL'
          REFRESH MATERIALIZED VIEW CONCURRENTLY public.nba_team_rolling_20_features;
          REFRESH MATERIALIZED VIEW CONCURRENTLY public.mlb_team_rolling_10_features;
          SQL
