name: Refresh Remote Materialized Views
on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *" # daily 04:30 UTC

jobs:
  refresh-matviews:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_POOLER }} # session-mode pooler URL
      PGSSLMODE: require

    steps:
      - uses: actions/checkout@v4

      - name: Ensure psql ≥15 (already 16 on ubuntu-latest, but keep explicit)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y postgresql-client

      - name: Refresh NBA & MLB materialized views
        run: |
          for q in \
            "REFRESH MATERIALIZED VIEW CONCURRENTLY public.nba_team_rolling_20_features;" \
            "REFRESH MATERIALIZED VIEW CONCURRENTLY public.mlb_team_rolling_10_features;" ; do
              psql -4 "$DATABASE_URL" --set ON_ERROR_STOP=on -c "$q"
          done
