name: Refresh Remote Materialized Views

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 4 * * *"

jobs:
  refresh-remote-matviews:
    runs-on: ubuntu-latest
    env:
      # Supabase service role key for CLI access
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      # Your Supabase project ref (found in your project URL)
      SUPABASE_PROJECT_REF: qaytaxyflvafblirxgdr

    steps:
      - uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Refresh NBA MV via Supabase CLI
        run: |
          supabase db query \
            "REFRESH MATERIALIZED VIEW CONCURRENTLY public.nba_team_rolling_20_features;" \
            --project-ref $SUPABASE_PROJECT_REF \
            --service-role-key "$SUPABASE_SERVICE_KEY"

      - name: Smoke-test NBA via Supabase CLI
        run: |
          supabase db query \
            "SELECT COUNT(*) AS cnt FROM public.nba_team_rolling_20_features;" \
            --project-ref $SUPABASE_PROJECT_REF \
            --service-role-key "$SUPABASE_SERVICE_KEY"

      - name: Refresh MLB MV via Supabase CLI
        run: |
          supabase db query \
            "REFRESH MATERIALIZED VIEW CONCURRENTLY public.mlb_team_rolling_10_features;" \
            --project-ref $SUPABASE_PROJECT_REF \
            --service-role-key "$SUPABASE_SERVICE_KEY"

      - name: Smoke-test MLB via Supabase CLI
        run: |
          supabase db query \
            "SELECT COUNT(*) AS cnt FROM public.mlb_team_rolling_10_features;" \
            --project-ref $SUPABASE_PROJECT_REF \
            --service-role-key "$SUPABASE_SERVICE_KEY"
