name: Refresh Remote Materialized Views

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 4 * * *"

jobs:
  refresh-remote-matviews:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PGSSLMODE: require

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client dnsutils

      - name: Resolve Supabase IPv4 address
        id: resolve
        run: |
          # extract host from DATABASE_URL
          HOST=$(echo "$DATABASE_URL" | sed -E 's#postgresql://[^@]+@([^:/]+).*#\1#')
          IPV4=$(dig +short A "$HOST" | head -1)
          echo "PGHOST=$IPV4" >> $GITHUB_ENV
          echo "Resolved $HOST → $IPV4"

      - name: Refresh NBA Materialized View
        run: |
          psql \
            "$DATABASE_URL" \
            --no-password \
            --set ON_ERROR_STOP=on \
            -c "REFRESH MATERIALIZED VIEW CONCURRENTLY public.nba_team_rolling_20_features;"

      - name: Smoke-test NBA View
        run: |
          psql \
            "$DATABASE_URL" \
            --no-password \
            --set ON_ERROR_STOP=on \
            -c "SELECT COUNT(*) FROM public.nba_team_rolling_20_features;"

      - name: Refresh MLB Materialized View
        run: |
          psql \
            "$DATABASE_URL" \
            --no-password \
            --set ON_ERROR_STOP=on \
            -c "REFRESH MATERIALIZED VIEW CONCURRENTLY public.mlb_team_rolling_10_features;"

      - name: Smoke-test MLB View
        run: |
          psql \
            "$DATABASE_URL" \
            --no-password \
            --set ON_ERROR_STOP=on \
            -c "SELECT COUNT(*) FROM public.mlb_team_rolling_10_features;"
